networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: chamirthiaparna/mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image: chamirthiaparna/catalogue:v1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb
  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
  user:
    image: chamirthiaparna/user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
  cart:
    image: chamirthiaparna/cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
  mysql:
    image: chamirthiaparna/mysql:v1
    container_name: mysql
    networks:
      - roboshop
  shipping:
    image: chamirthiaparna/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql 
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123 
  payment:
    image: chamirthiaparna/payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq        
  web:
    image: chamirthiaparna/web:v1
    container_name: web
    networks:
    - roboshop
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment